# Generated by Django 6.0.6 on 2026-06-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='media/stdent_img')),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('civil', 'CIVIL')], max_length=10)),
            ],
        ),
    ]
